from .studentManagementModel import *
from .batchmanagementModel import *
from .maintianLoginModel import *
from .groupbatchmanagementModel import *
from .clusterbatchmanagementModel import *
from .papermanagementModel import *
from .settingModel import *
from .authorityManagementModel import *
from .rolesMangementModel import *
from .reourceManagementModel import *
from .adminProfileManagementModel import *
from .courseManagementModel import *
from .questionBankManagementModel import *
from .examManagementModel import *
from .resultManagementModel import *
from .requestHeadingModel import *
from .languageMangementModel import * 
from .country_state_districtModel import *