# Generated by Django 3.1.3 on 2021-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionbank_question',
            name='QuestionBank_Question Constraint',
        ),
        migrations.AddConstraint(
            model_name='questionbank_question',
            constraint=models.UniqueConstraint(fields=('refrence_Questions_Type_Detail', 'selectLanguage', 'question', 'optionList'), name='QuestionBank_Question Constraint'),
        ),
    ]
