# Generated by Django 3.1.3 on 2021-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0003_auto_20210611_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papermanagement',
            name='noOfSets',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Paper Remarks'),
        ),
    ]
