# Generated by Django 3.1.3 on 2021-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0004_auto_20210613_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papermanagement',
            name='noOfSets',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='No of Sets'),
        ),
        migrations.AlterField(
            model_name='papermanagement',
            name='paperRemark',
            field=models.TextField(blank=True, default='Done', null=True, verbose_name='Paper Remarks'),
        ),
    ]
