# Generated by Django 3.1.3 on 2021-06-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0005_auto_20210613_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtmanagement',
            name='batchPressor',
        ),
        migrations.RemoveField(
            model_name='batchtmanagement',
            name='batchSuccessor',
        ),
        migrations.RemoveField(
            model_name='batchtmanagement',
            name='batchSuperVisorID',
        ),
        migrations.RemoveField(
            model_name='batchtmanagement',
            name='batchSuperVisorName',
        ),
        migrations.AddField(
            model_name='batchtmanagement',
            name='batchCourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='saletoApp.courses', verbose_name='Batch Course Name'),
        ),
        migrations.AddField(
            model_name='batchtmanagement',
            name='batchCourseType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='saletoApp.type_of_course', verbose_name='Batch Course Type'),
        ),
    ]
