# Generated by Django 3.1.3 on 2021-06-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0006_auto_20210621_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtmanagement',
            name='batchID',
            field=models.CharField(max_length=50, unique=True, verbose_name='Batch ID'),
        ),
        migrations.AlterField(
            model_name='batchtmanagement',
            name='batchName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Bacth Name'),
        ),
    ]
