# Generated by Django 3.1.3 on 2021-06-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0007_auto_20210621_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtmanagement',
            name='batchYear',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Batch Year'),
        ),
        migrations.AlterField(
            model_name='batchtmanagement',
            name='batchDescription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Batch Description'),
        ),
    ]
