# Generated by Django 3.1.3 on 2021-06-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0009_eaxm_paper_batchmanagement_mtwom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eaxm_paper',
            name='batchManagement_mtwom',
        ),
        migrations.AddField(
            model_name='exammanagement',
            name='batchManagement_mtwom',
            field=models.ManyToManyField(blank=True, to='saletoApp.BatchtManagement'),
        ),
        migrations.AddField(
            model_name='exammanagement',
            name='examAssociateCourseType',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='saletoApp.type_of_course'),
            preserve_default=False,
        ),
    ]
