# Generated by Django 3.1.3 on 2021-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0010_auto_20210624_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanagement',
            name='examPassword',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Exam Password'),
        ),
    ]
