# Generated by Django 3.1.3 on 2021-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0011_auto_20210624_1446'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exammanagement',
            name='ExamManagement Management',
        ),
        migrations.AlterField(
            model_name='exammanagement',
            name='examID',
            field=models.CharField(max_length=50, unique=True, verbose_name='Exam ID'),
        ),
    ]
