# Generated by Django 3.1.3 on 2021-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0012_auto_20210624_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanagement',
            name='batchManagement_mtwom',
            field=models.ManyToManyField(to='saletoApp.BatchtManagement'),
        ),
    ]
