# Generated by Django 3.1.3 on 2021-06-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0013_auto_20210624_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcemanagement',
            old_name='referUser',
            new_name='refrence_user',
        ),
        migrations.CreateModel(
            name='RolesUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courseType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saletoApp.rolesmanagement')),
            ],
        ),
    ]
