# Generated by Django 3.1.3 on 2021-06-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saletoApp', '0014_auto_20210628_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcemanagement',
            old_name='refrence_user',
            new_name='referUser',
        ),
    ]
